version: 2.1

orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.2.6

jobs:
  test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Linting check
          command: flake8
      - run:
          name: Run tests
          command: pytest
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKER_USER/oc-lettings:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker tag $DOCKER_USER/oc-lettings:$CIRCLE_SHA1 $DOCKER_USER/oc-lettings:latest
            docker push $DOCKER_USER/oc-lettings:$CIRCLE_SHA1
            docker push $DOCKER_USER/oc-lettings:latest


workflows:
  sample:
    jobs:
      - test
      - build
