version: 2.1

orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.2.6

jobs:
  run-tests:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: mkdir src/staticfiles
      - run: flake8
      - run: pytest
  build-docker-image:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKER_USER/oc-lettings:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $DOCKER_USER/oc-lettings:latest
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-on-docker-hub:
    docker:
      - image: cimg/base:2022.06
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker image to Docker Hub
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker tag $DOCKER_USER/oc-lettings:latest $DOCKER_USER/oc-lettings:$CIRCLE_SHA1
            docker push $DOCKER_USER/oc-lettings:$CIRCLE_SHA1
            docker push $DOCKER_USER/oc-lettings:latest
  deploy-on-heroku:
    executor: heroku/default
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - heroku/install
      - run: heroku container:login
      - run:
          name: Push Docker image to registry
          command: |
            docker tag $DOCKER_USER/oc-lettings:latest registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
      - heroku/release-docker-image:
          process-types: web

workflows:
  main:
    jobs:
      - run-tests
      - build-docker-image:
          requires:
            - run-tests
          filters:
            branches:
              only: master
      - publish-on-docker-hub:
          requires:
            - build-docker-image
          filters:
            branches:
              only: master
      - deploy-on-heroku:
          requires:
            - build-docker-image
          filters:
            branches:
              only: master
