version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Linting
          command: flake8
      - run:
          name: Tests
          command: pytest
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

      - run: docker build -t $DOCKER_USER/oc-lettings:$CIRCLE_SHA1 .

      - run: docker push $DOCKER_USER/oc-lettings:$CIRCLE_SHA1

workflows:
  sample:
    jobs:
      - test
      - build
